# Prometheus configuration for Database Automation Suite
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'database-automation-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/prometheus-rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Database Automation Suite metrics
  - job_name: 'database-automation'
    static_configs:
      - targets: ['db-automation:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL Exporter (if available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: '/metrics'
    scrape_interval: 30s
    honor_labels: true

  # Node Exporter (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # cAdvisor for container metrics (if available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

# Remote write configuration (optional)
# remote_write:
#   - url: "https://your-remote-prometheus-url/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration (optional)
# remote_read:
#   - url: "https://your-remote-prometheus-url/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"