apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: database-automation-hpa
  namespace: database-automation
  labels:
    app.kubernetes.io/name: database-automation
    app.kubernetes.io/component: hpa
    app.kubernetes.io/part-of: database-automation-suite
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: database-automation
  
  minReplicas: 1
  maxReplicas: 3
  
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # Custom metrics scaling (if metrics server supports custom metrics)
  - type: Pods
    pods:
      metric:
        name: database_connection_pool_usage
      target:
        type: AverageValue
        averageValue: "80"
  
  # External metrics scaling (e.g., based on queue length)
  - type: External
    external:
      metric:
        name: database_automation_backup_queue_length
        selector:
          matchLabels:
            service: database-automation
      target:
        type: Value
        value: "10"

  # Scaling behavior configuration
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      selectPolicy: Min
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
    
    scaleUp:
      stabilizationWindowSeconds: 60   # 1 minute
      selectPolicy: Max
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30

---
# Vertical Pod Autoscaler (if VPA is installed)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: database-automation-vpa
  namespace: database-automation
  labels:
    app.kubernetes.io/name: database-automation
    app.kubernetes.io/component: vpa
    app.kubernetes.io/part-of: database-automation-suite
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: database-automation
  
  updatePolicy:
    updateMode: "Auto"  # or "Initial" or "Off"
  
  resourcePolicy:
    containerPolicies:
    - containerName: database-automation
      maxAllowed:
        cpu: 4000m
        memory: 8Gi
      minAllowed:
        cpu: 500m
        memory: 1Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
    
    - containerName: log-shipper
      maxAllowed:
        cpu: 500m
        memory: 512Mi
      minAllowed:
        cpu: 50m
        memory: 64Mi
      controlledResources: ["cpu", "memory"]