apiVersion: v1
kind: Secret
metadata:
  name: database-automation-secrets
  namespace: database-automation
  labels:
    app.kubernetes.io/name: database-automation
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: database-automation-suite
    app.kubernetes.io/managed-by: kubernetes
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # Use: echo -n "your-password" | base64
  
  # PostgreSQL credentials
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  POSTGRES_REPLICA_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  
  # Email/SMTP credentials
  SMTP_PASSWORD: ZW1haWxwYXNzd29yZA==  # emailpassword
  
  # AWS credentials for S3 backup storage
  AWS_ACCESS_KEY_ID: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=  # AKIAIOSFODNN7EXAMPLE
  AWS_SECRET_ACCESS_KEY: d0phbEdYbFJLdG5GYU1JNHNhdGFJUkNXNzU4OXdPeTVVUFhhdEI=  # wJalGXlRKtnFaMI4sataIRCW7589wOy5UPXatB
  
  # Database encryption key
  DATABASE_ENCRYPTION_KEY: bXktc2VjcmV0LWVuY3J5cHRpb24ta2V5LTMyLWNoYXJzaGVyZQ==  # my-secret-encryption-key-32-charshere
  
  # Application secret key
  SECRET_KEY: bXktYXBwbGljYXRpb24tc2VjcmV0LWtleS1oZXJl  # my-application-secret-key-here

---
# External secrets (if using external secret management)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: database-automation
spec:
  provider:
    vault:
      server: "https://vault.company.internal"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "database-automation"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-automation-external-secrets
  namespace: database-automation
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: database-automation-vault-secrets
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: database-automation/postgres
      property: password
  - secretKey: smtp-password
    remoteRef:
      key: database-automation/email
      property: smtp-password
  - secretKey: aws-access-key-id
    remoteRef:
      key: database-automation/aws
      property: access-key-id
  - secretKey: aws-secret-access-key
    remoteRef:
      key: database-automation/aws
      property: secret-access-key