apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-automation
  namespace: database-automation
  labels:
    app.kubernetes.io/name: database-automation
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: database-automation-suite
    app.kubernetes.io/managed-by: kubernetes
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: database-automation
  name: database-automation-role
  labels:
    app.kubernetes.io/name: database-automation
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: database-automation-suite
rules:
# Allow reading secrets and configmaps
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]

# Allow reading pods and services for service discovery
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]

# Allow creating events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

# Allow reading persistent volume claims for backup storage
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]

# Allow reading deployments and replicasets for health monitoring
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: database-automation-rolebinding
  namespace: database-automation
  labels:
    app.kubernetes.io/name: database-automation
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: database-automation-suite
subjects:
- kind: ServiceAccount
  name: database-automation
  namespace: database-automation
roleRef:
  kind: Role
  name: database-automation-role
  apiGroup: rbac.authorization.k8s.io

---
# ClusterRole for cross-namespace monitoring (optional)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: database-automation-cluster-role
  labels:
    app.kubernetes.io/name: database-automation
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: database-automation-suite
rules:
# Allow reading nodes for system monitoring
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

# Allow reading persistent volumes
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]

# Allow reading storage classes
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: database-automation-cluster-rolebinding
  labels:
    app.kubernetes.io/name: database-automation
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: database-automation-suite
subjects:
- kind: ServiceAccount
  name: database-automation
  namespace: database-automation
roleRef:
  kind: ClusterRole
  name: database-automation-cluster-role
  apiGroup: rbac.authorization.k8s.io